# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_accounttest_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала тестирования'),
        ),
    ]
