# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170728_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150, verbose_name='Токен для авторизации')),
            ],
        ),
        migrations.AlterField(
            model_name='accounttest',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email тестируемого'),
        ),
        migrations.AddField(
            model_name='token',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_account', to='quiz.AccountTest', verbose_name='Токен для аккаунта'),
        ),
    ]
